# Generated by Django 2.0 on 2019-07-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190714_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anacategory',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='kategori adı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='kategori adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ürün adı'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
