# Generated by Django 2.0 on 2019-07-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargo',
            name='bankacılık_bedeli',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
