# Generated by Django 2.0 on 2019-07-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190714_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kargo_tipi',
            field=models.CharField(choices=[('1', 'Kapıda Nakit Ödemeli Kargo'), ('2', 'Kapıda Tek Çekim Kredi Kartı Ödemeli Kargo'), ('3', 'EFT Ödemeli Kargo')], default=1, help_text='Blabla', max_length=10, verbose_name='Kargo Tercihiniz:'),
            preserve_default=False,
        ),
    ]
