# Generated by Django 2.0 on 2019-07-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_kargo_tipi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Adres:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[['1', 'Adana'], ['2', 'Adıyaman'], ['3', 'Afyonkarahisar'], ['4', 'Ağrı'], ['5', 'Aksaray'], ['6', 'Amasya'], ['7', 'Ankara'], ['8', 'Antalya'], ['9', 'Ardahan'], ['10', 'Artvin'], ['11', 'Aydın'], ['12', 'Balıkesir'], ['13', 'Bartın'], ['14', 'Batman'], ['15', 'Bayburt'], ['16', 'Bilecik'], ['17', 'Bingöl'], ['18', 'Bitlis'], ['19', 'Bolu'], ['20', 'Burdur'], ['21', 'Bursa'], ['22', 'Çanakkale'], ['23', 'Çankırı'], ['24', 'Çorum'], ['25', 'Denizli'], ['26', 'Diyarbakır'], ['27', 'Düzce'], ['28', 'Edirne'], ['29', 'Elazığ'], ['30', 'Erzincan'], ['31', 'Erzurum'], ['32', 'Eskişehir'], ['33', 'Gaziantep'], ['34', 'Giresun'], ['35', 'Gümüşhane'], ['36', 'Hakkâri'], ['37', 'Hatay'], ['38', 'Iğdır'], ['39', 'Isparta'], ['40', 'İstanbul'], ['41', 'İzmir'], ['42', 'Kahramanmaraş'], ['43', 'Karabük'], ['44', 'Karaman'], ['45', 'Kars'], ['46', 'Kastamonu'], ['47', 'Kayseri'], ['48', 'Kilis'], ['49', 'Kırıkkale'], ['50', 'Kırklareli'], ['51', 'Kırşehir'], ['52', 'Kocaeli'], ['53', 'Konya'], ['54', 'Kütahya'], ['55', 'Malatya'], ['56', 'Manisa'], ['57', 'Mardin'], ['58', 'Mersin'], ['59', 'Muğla'], ['60', 'Muş'], ['61', 'Nevşehir'], ['62', 'Niğde'], ['63', 'Ordu'], ['64', 'Osmaniye'], ['65', 'Rize'], ['66', 'Sakarya'], ['67', 'Samsun'], ['68', 'Şanlıurfa'], ['69', 'Siirt'], ['70', 'Sinop'], ['71', 'Sivas'], ['72', 'Şırnak'], ['73', 'Tekirdağ'], ['74', 'Tokat'], ['75', 'Trabzon'], ['76', 'Tunceli'], ['77', 'Uşak'], ['78', 'Van'], ['79', 'Yalova'], ['80', 'Yozgat'], ['81', 'Zonguldak']], max_length=10, verbose_name='Şehir:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Adınız:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Soyadınız:'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Sipariş'),
        ),
    ]
